"""changed aggregated 

Revision ID: 0127a79d13a8
Revises: eb74ecacb871
Create Date: 2024-10-02 12:58:09.494142

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0127a79d13a8'
down_revision = 'eb74ecacb871'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('aggregated_data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('driving_score', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('driving_category', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('aggregated_data', schema=None) as batch_op:
        batch_op.drop_column('driving_category')
        batch_op.drop_column('driving_score')

    # ### end Alembic commands ###
