"""empty message

Revision ID: 98c1bfd8298b
Revises: 53b4a9f81f5b
Create Date: 2024-09-27 14:19:05.817493

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '98c1bfd8298b'
down_revision = '53b4a9f81f5b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('driver', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.String(length=120), nullable=False))
        batch_op.add_column(sa.Column('password_hash', sa.String(length=128), nullable=False))
        batch_op.add_column(sa.Column('identity_proof', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('accepted_terms', sa.Boolean(), nullable=False))
        batch_op.create_unique_constraint(None, ['email'])

    with op.batch_alter_table('trip', schema=None) as batch_op:
        batch_op.alter_column('gps_data',
               existing_type=sa.TEXT(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trip', schema=None) as batch_op:
        batch_op.alter_column('gps_data',
               existing_type=sa.TEXT(),
               nullable=False)

    with op.batch_alter_table('driver', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('accepted_terms')
        batch_op.drop_column('identity_proof')
        batch_op.drop_column('password_hash')
        batch_op.drop_column('email')

    # ### end Alembic commands ###
