"""Updated AggregatedData model

Revision ID: e1e69aa54202
Revises: 8c50840d1526
Create Date: 2024-09-29 13:39:27.235676

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e1e69aa54202'
down_revision = '8c50840d1526'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('aggregated_data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('avg_speed_max', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('avg_speed_std', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('aggregated_data', schema=None) as batch_op:
        batch_op.drop_column('avg_speed_std')
        batch_op.drop_column('avg_speed_max')

    # ### end Alembic commands ###
