"""Added speed_violation_count and total_observations to AggregatedData model

Revision ID: e9d8eb412856
Revises: dba25a6e1f9d
Create Date: 2024-09-29 13:59:58.630452

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e9d8eb412856'
down_revision = 'dba25a6e1f9d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('aggregated_data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total_observations', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('aggregated_data', schema=None) as batch_op:
        batch_op.drop_column('total_observations')

    # ### end Alembic commands ###
