"""changed aggregated 

Revision ID: eb74ecacb871
Revises: e9d8eb412856
Create Date: 2024-10-02 12:44:32.926636

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eb74ecacb871'
down_revision = 'e9d8eb412856'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('aggregated_data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date', sa.Date(), nullable=False))
        batch_op.drop_column('risk_level')
        batch_op.drop_column('total_distance')
        batch_op.drop_column('avg_score')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('aggregated_data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('avg_score', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('total_distance', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('risk_level', sa.VARCHAR(length=50), nullable=True))
        batch_op.drop_column('date')

    # ### end Alembic commands ###
